export default {
  version: 1,
  info: { id: 'QsqGadqfbQWS8Q0A', name: 'Blendarrrrrr', created: 1725761416864, updated: 1725761416864 },
  nodes: [
    {
      id: '-ha-J2-vISltOm4i',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_Alternate_PolyesterFabric_C' },
      position: { x: 1356, y: 276 },
    },
    {
      id: '9THbyDzQxAykYTC3',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_Alternate_DilutedFuel_C', rotIdx: 1 },
      position: { x: 984, y: 750 },
    },
    {
      id: 'Iu5f-b7bTaeaNYsV',
      type: 'item',
      data: { speedThou: 30000, interfaceKind: 'both', itemKey: 'Desc_Fabric_C' },
      position: { x: 1782, y: 336 },
    },
    {
      id: 'LpzQ6fLFoR-ItEKt',
      type: 'item',
      data: { speedThou: 130000, interfaceKind: 'both', itemKey: 'Desc_Water_C' },
      position: { x: 720, y: 336 },
    },
    {
      id: 'TvBJWKlYO5XWgSpP',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'pipeJunc' },
      position: { x: 930, y: 336 },
    },
    {
      id: 'i3SN3dHSD2JAym99',
      type: 'item',
      data: { speedThou: 50000, interfaceKind: 'both', itemKey: 'Desc_HeavyOilResidue_C' },
      position: { x: 720, y: 486 },
    },
    {
      id: 'jXYp7hsLut1mVf3S',
      type: 'item',
      data: { speedThou: 100000, interfaceKind: 'both', itemKey: 'Desc_LiquidFuel_C', rotIdx: 3 },
      position: { x: 1320, y: 750 },
    },
    {
      id: 'twRKeNfYTxHQPofl',
      type: 'item',
      data: { speedThou: 30000, interfaceKind: 'both', itemKey: 'Desc_PolymerResin_C' },
      position: { x: 720, y: 216 },
    },
  ],
  edges: [
    {
      id: 'Aq2lUtDYzm9eddnA',
      type: 'belt',
      source: 'twRKeNfYTxHQPofl',
      target: '-ha-J2-vISltOm4i',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'CYFb8_JOS4r410Kr',
      type: 'pipe',
      source: '9THbyDzQxAykYTC3',
      target: 'jXYp7hsLut1mVf3S',
      sourceHandle: 'right-fluid-out-1',
      targetHandle: 'left-fluid-in-0',
    },
    {
      id: 'ezrQkfSuILigCqrm',
      type: 'pipe',
      source: 'i3SN3dHSD2JAym99',
      target: '9THbyDzQxAykYTC3',
      sourceHandle: 'right-fluid-out-0',
      targetHandle: 'left-fluid-in-3',
    },
    {
      id: 'ntST8xs86cVeOCc9',
      type: 'pipe',
      source: 'TvBJWKlYO5XWgSpP',
      target: '-ha-J2-vISltOm4i',
      sourceHandle: 'right-fluid-out-0',
      targetHandle: 'left-fluid-in-1',
    },
    {
      id: 'p3VOqaI4xiPGBmwv',
      type: 'pipe',
      source: 'LpzQ6fLFoR-ItEKt',
      target: 'TvBJWKlYO5XWgSpP',
      sourceHandle: 'right-fluid-out-0',
      targetHandle: 'left-fluid-in-0',
    },
    {
      id: 'sXED4PHZRMzIa1_e',
      type: 'belt',
      source: '-ha-J2-vISltOm4i',
      target: 'Iu5f-b7bTaeaNYsV',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'yBVFtJUXqhVuqkYP',
      type: 'pipe',
      source: 'TvBJWKlYO5XWgSpP',
      target: '9THbyDzQxAykYTC3',
      sourceHandle: 'bottom-fluid-out-0',
      targetHandle: 'left-fluid-in-2',
    },
  ],
  properties: { viewportX: -20.879604194070453, viewportY: -51.47950679411878, viewportZoom: 0.753667454779189 },
};
