export default {
  nodes: [
    {
      id: '-kFW0_k0UaCLiMiN',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_IronRod_C', rotIdx: 3 },
      position: { x: 1326, y: 168 },
    },
    {
      id: '00oVM7LOfdeoq37y',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'splitter' },
      position: { x: 1686, y: -306 },
    },
    {
      id: '36aEjWC4FRlHV4_P',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'splitter' },
      position: { x: 978, y: 690 },
    },
    {
      id: '7Lgz2hoHdCyZvYMR',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_Screw_C', rotIdx: 1 },
      position: { x: 2028, y: 174 },
    },
    {
      id: '9no2X_unrLinSyNs',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'splitter' },
      position: { x: 1326, y: 690 },
    },
    {
      id: 'FH5sg-RzWo2_nr95',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'merger' },
      position: { x: 2310, y: 690 },
    },
    {
      id: 'I5XrBFifmO3j-zsi',
      type: 'item',
      data: { speedThou: 30000, interfaceKind: 'both', itemKey: 'Desc_IronIngot_C' },
      position: { x: 660, y: 690 },
    },
    {
      id: 'Lge0TU0skMb1MPiT',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_Screw_C', rotIdx: 1 },
      position: { x: 1686, y: 174 },
    },
    {
      id: 'PH3QsN-VUpDRzfvY',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'merger' },
      position: { x: 2028, y: 690 },
    },
    {
      id: '_22avgPcZVKnzkti',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'merger' },
      position: { x: 1686, y: 690 },
    },
    {
      id: 'b_ogjtRaWd4tlnSc',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'merger' },
      position: { x: 978, y: -306 },
    },
    {
      id: 'm5boEZtIhv28ZKoc',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_Screw_C', rotIdx: 1 },
      position: { x: 2310, y: 174 },
    },
    {
      id: 'p9jVVxZhHUPoTMsF',
      type: 'recipe',
      data: { clockSpeedThou: 10000000, recipeKey: 'Recipe_IronRod_C', rotIdx: 3 },
      position: { x: 978, y: 168 },
    },
    {
      id: 'pO99Z6Xw1gwnoVc_',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'splitter' },
      position: { x: 2028, y: -306 },
    },
    {
      id: 'pe8Zk59_FyZ2QoNk',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'merger' },
      position: { x: 1326, y: -306 },
    },
    {
      id: 'v7VgDusNsBK9WBGC',
      type: 'item',
      data: { speedThou: 120000, interfaceKind: 'both', itemKey: 'Desc_IronScrew_C' },
      position: { x: 2598, y: 690 },
    },
    {
      id: 'yonWMSwyqohpEB0Z',
      type: 'logistic',
      data: { smartProRules: { right: ['any'] }, pipeJuncInt: {}, type: 'splitter' },
      position: { x: 2310, y: -306 },
    },
  ],
  edges: [
    {
      id: '4hhXA7CKZg8IO-xE',
      type: 'belt',
      source: 'PH3QsN-VUpDRzfvY',
      target: 'FH5sg-RzWo2_nr95',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: '4putNJSzgqLLrAdq',
      type: 'belt',
      source: 'yonWMSwyqohpEB0Z',
      target: 'm5boEZtIhv28ZKoc',
      sourceHandle: 'bottom-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'ED7zivZ6aPZkzmYG',
      type: 'belt',
      source: 'FH5sg-RzWo2_nr95',
      target: 'v7VgDusNsBK9WBGC',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'HCJQjwImcxNf_m7Z',
      type: 'belt',
      source: 'pe8Zk59_FyZ2QoNk',
      target: '00oVM7LOfdeoq37y',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'MQmIxtr5hHg_yHur',
      type: 'belt',
      source: 'I5XrBFifmO3j-zsi',
      target: '36aEjWC4FRlHV4_P',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'Nt90HssVJ7AC4m7-',
      type: 'belt',
      source: 'Lge0TU0skMb1MPiT',
      target: '_22avgPcZVKnzkti',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'top-solid-in-0',
    },
    {
      id: 'QIpZA36N97bx9DWd',
      type: 'belt',
      source: '_22avgPcZVKnzkti',
      target: 'PH3QsN-VUpDRzfvY',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'SmRPmKmN1LmuXlyI',
      type: 'belt',
      source: '36aEjWC4FRlHV4_P',
      target: '9no2X_unrLinSyNs',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'TpAXFtW3PU7X_y_o',
      type: 'belt',
      source: 'pO99Z6Xw1gwnoVc_',
      target: '7Lgz2hoHdCyZvYMR',
      sourceHandle: 'bottom-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'Vz48IdFtfv71VrSJ',
      type: 'belt',
      source: 'b_ogjtRaWd4tlnSc',
      target: 'pe8Zk59_FyZ2QoNk',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'XWli-MkG58tdx6Sz',
      type: 'belt',
      source: '36aEjWC4FRlHV4_P',
      target: 'p9jVVxZhHUPoTMsF',
      sourceHandle: 'top-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'YJMLUKBDq1gwnx5s',
      type: 'belt',
      source: '9no2X_unrLinSyNs',
      target: '-kFW0_k0UaCLiMiN',
      sourceHandle: 'top-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: '_3uWd6m2472a7Rv5',
      type: 'belt',
      source: 'pO99Z6Xw1gwnoVc_',
      target: 'yonWMSwyqohpEB0Z',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'jthCnVDIfUnV3yAv',
      type: 'belt',
      source: '00oVM7LOfdeoq37y',
      target: 'pO99Z6Xw1gwnoVc_',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 'nxFg1_JesjX4Q6Iw',
      type: 'belt',
      source: 'p9jVVxZhHUPoTMsF',
      target: 'b_ogjtRaWd4tlnSc',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'bottom-solid-in-0',
    },
    {
      id: 'oyTDSKWWHIGn6g8C',
      type: 'belt',
      source: '00oVM7LOfdeoq37y',
      target: 'Lge0TU0skMb1MPiT',
      sourceHandle: 'bottom-solid-out-0',
      targetHandle: 'left-solid-in-0',
    },
    {
      id: 't2ZPPTcB3qjQjdKz',
      type: 'belt',
      source: 'm5boEZtIhv28ZKoc',
      target: 'FH5sg-RzWo2_nr95',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'top-solid-in-0',
    },
    {
      id: 'uULET-CSWBwDvxKk',
      type: 'belt',
      source: '7Lgz2hoHdCyZvYMR',
      target: 'PH3QsN-VUpDRzfvY',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'top-solid-in-0',
    },
    {
      id: 'yNRs45l813y8VcOX',
      type: 'belt',
      source: '-kFW0_k0UaCLiMiN',
      target: 'pe8Zk59_FyZ2QoNk',
      sourceHandle: 'right-solid-out-0',
      targetHandle: 'bottom-solid-in-0',
    },
  ],
};
